name: Build

on:
  workflow_dispatch:
  push: 
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/build.yaml'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: m365pnp/spfx:1.14.0
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: gulp bundle --ship
      - run: ls
