name: Build

on:
  workflow_dispatch:
  push: 
    branches:
      - dev
    paths:
      - 'src/**'
      - 'workspaces/codespaces-test-04/.github/workflows/build.yaml'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: m365pnp/spfx:1.14.0
    steps:
      - run: npm install
      - run: gulp bundle --ship
      - run: ls
